# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wepay' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Wepay
  pod 'IQKeyboardManager'	

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

end
